# Tem que fazer o esqueminha de pegar as variáveis de ambiente ${Var}


# spring.application.name=estoque
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${USER}
# spring.datasource.password=${PASSWORD}
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true